name: CI - Build and push to AWS ECR
on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  IMAGE_VERSION: "v1.0.0"
  AWS_REGION: "us-east-1"
jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, y push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} .
          docker tag $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} $ECR_REGISTRY/${{ env.IMAGE_NAME }}:latest
          docker tag $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          docker push $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          docker push $ECR_REGISTRY/${{ env.IMAGE_NAME }}:latest
          docker push $ECR_REGISTRY/${{ env.IMAGE_NAME }}:${{ github.sha }}